### ISSUE TITLE
Upgrade PhPeace

### ISSUE THREAD

**Issue by serverok** [peacelink/phpeace#8]
We have PhPeace installation that is using older version. How to we upgrade it to latest version. We replaced files, but getting SQL errors related to missing table fieleds.

Is there any upgrade script available for upgrading database structure ?

**Comment by fra967** [comment]
please provide details about PhPeace version and SQL error

**Comment by serverok** [comment]
I am not really sure what version we used in old site. From admin page, it look like 

> Powered by PhPeace 2.5.5

http://admin.italiantouristoffice.se/gate/index.php

Now  on a test server (not on live) we uploaded all PHP files, run the upgrade script.

```
[root@ip-172-31-17-131 phpeace]# pwd
/home/italiantouristoffice.se/scripts/phpeace
[root@ip-172-31-17-131 phpeace]# php -v
PHP 5.3.3 (cli) (built: Mar 22 2017 12:27:09) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
[root@ip-172-31-17-131 phpeace]# cat phpeace_update.sh 
#! /bin/sh

CURRENTDIR=`dirname $0`
cd $CURRENTDIR

php $CURRENTDIR/phpeace_update.php


[root@ip-172-31-17-131 phpeace]# ./phpeace_update.sh
Executed update 260
[root@ip-172-31-17-131 phpeace]#
```

Now when i login to admin area. i get error

```
sql: 'SELECT name,phone,mobile,email,email_visible,signature,active,user_show,login,
id_geo,notes,admin_notes,id_language,connections,UNIX_TIMESTAMP(start_date) AS start_date_ts,id_p,
UNIX_TIMESTAMP(last_conn) AS last_conn_ts,id_tutor,verified,bounces,photo_visible
FROM users u INNER JOIN user_notes USING(id_user) WHERE u.id_user=\'3\''
error_number: 1054
error: 'Unknown column \'photo_visible\' in \'field list\''
```

See screenshot with full error.

![phpeace](https://user-images.githubusercontent.com/34412323/47351363-6ffc8b80-d6d5-11e8-901d-12e3fc9421e2.png)

We can add these fileds back, but i am not sure that is the correct away as there can be more missing and we may face problem once we make it live. Here are some fileds we found missing.

```
users.photo_visible
topics.newsletter_people
modules.global
docs_articles.id_subtopic_form
```

There maybe more, this is what we found so far.

**Comment by fra967** [comment]
italiantouristoffice.se & italiantouristboard.co.uk were on a PhPeace fork, they cannot be upgraded using this repository, they should be left as they are.
In any case, the upgrade process would require the registration with a PhPeace running in server mode, which will then distribute all the automatic scripts and database upgrades.
The only live PhPeace server that we actively maintain is updates.phpeace.org, based on this repository, but it's not applicable to the italiantouristoffice fork.
